language: generic
sudo: required
services:
  - docker

before_install:
  - docker build -t shanemcg/docker_udemy -f Dockerfile.dev .

script:
  - cd frontend
  - docker run -e CI=true shanemcg/docker-react npm run test